name: env-vars-workflow
on:
    workflow_dispatch:
    push:
      branches:
        - dev-ps
run-name: "env-vars ${{ github.ref }} , by ${{github.actor}}"
env:
    WF_LEVEL_ENV: Available to all jobs ### Workflow level environment variable
jobs:
    display-env-vars:
        runs-on: ubuntu-latest
        env:
            JOB_LEVEL_ENV: "Available to all steps in this job" ### Job level environment variable
        steps:
            - name: Log Environment Variables
              run: echo "$GITHUB_REF"
              ### This will get eveluate in runner machine
              #  output of above run looks like:
              #    Run echo "$GITHUB_REF" ## Its getting evaluated in runner machine
              #     refs/heads/dev-ps
              
               
            
            - name: Log context env variable
              ### This will get evelualted by github action before sending to runner machine
              run: echo "${{ github.ref }}"
                
                    # output of above run looks like:
                    #    Run echo "refs/heads/dev-ps"  ## Its getting evaluated by github action
                    #    refs/heads/dev-ps
            - name: Log Custome env vars
              env:
                STEP_LEVEL_ENV: Available only to this step ### Step level environment variable
                WF_LEVEL_ENV: Overridden at step level ### Overriding workflow level env var at step level
            run: |
                  echo "Workflow Level Env Var: ${{ env.WF_LEVEL_ENV }}" ##if condition we can apply
                  echo "Job Level Env Var: ${{ env.JOB_LEVEL_ENV }}"
                  echo "Step Level Env Var: ${{ env.STEP_LEVEL_ENV }}"