name: env-vars-workflow
on:
    workflow_dispatch:
    push:
      branches:
        - dev-ps
run-name: "env-vars ${{ github.ref }} , by ${{github.actor}}"
jobs:
    display-env-vars:
        runs-on: ubuntu-latest
        steps:
            - name: Log Environment Variables
              ### This will get eveluate in runner machine
              run: echo "$GITHUB_REF"
            - name: Log context env variable
              ### This will get evelualted by github action before sending to runner machine
              run: echo "${{ github.ref }}"