name: Variables and Secretes Workflow
on:
    workflow_dispatch:
    push:
      branches:
        - dev-ps
run-name: "var-secrets ${{ github.ref }} , by ${{github.actor}}"
jobs:
    log-vars:
        ### vars  context is used to access organization,environment or repository level variables
        runs-on: ${{ vars.JOBS_RUNNER}} ## Using Organization level variable
        env:
            ### secrets context is used to access organization,environment or repository level secrets
            
            Boolean_secret: ${{ secrets.BOOLEAN_SECRET }}  ## Accessing environment level secret
            Env_level_vars: ${{ vars.ENV_LEVEL_VAR }}  ## Accessing environment level variable
            Repo_level_vars: ${{ vars.REPO_LEVEL_VAR }} ### Accessing repository level variable
        steps:
            - name: Runs only if Boolean_secret is false
              if: ${{ env.Boolean_secret == 'False' }}
              run: |
                  echo "Boolean Secret is false, so this step is running"
                  echo "Environment Level Variable: ${{ env.Env_level_vars }}"
                  echo "Repository Level Variable: ${{ env.Repo_level_vars }}"