name: Composite Action Workflow 
on: 
    workflow_dispatch:
    push:
        branches:
          - dev-ps
        
        paths:
          - 'nodejs-workflow/**'

env:
    PROJECT_DIR: ./nodejs-workflow  ## Set environment variable for project directory

jobs:
    Install-nodejs-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                ref: dev-ps
                ### applying custom action####
            - name: npm install & cache dependencies ## this will use custom action from .github/actions/npm-and-cached
              uses: ./.github/actions/npm-and-cached ## custom action to cache and load dependencies
                ### completing custom action####
    deploy-job: 
         needs: Install-nodejs-dependencies 
         runs-on: ubuntu-latest
         steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                ref: dev-ps
            - name: install nodejs
              uses: actions/setup-node@v6
              with:
                node-version: '24.x' 
            ## To install whole node_modulew folder in cache we can use below step
            - name: cache node_modules ## to remove same installtion again in below jobs.
              uses: actions/cache@v5
              id: cache-node-modules
              with:
                path: ${{ env.PROJECT_DIR }}/node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true' ## this step will run only if cache is not hit
              working-directory: ${{ env.PROJECT_DIR }}
              run: |
                pwd
                npm i --legacy-peer-deps
                npm i --package-lock-only
                npm ci
                npm i env-cmd
            - name: Deploy Application
              run: echo "Deploying React Application..."
    job_info:
        needs: [deploy-job, Install-nodejs-dependencies] ## this job will run only after successful completion of both 'deploy-job' and 'Install-nodejs-dependencies'
        runs-on: ubuntu-latest
        steps:
            - name: Output github context
              run: echo "${{ toJson(github) }}"

