name: Docker Workflow
on:
  workflow_dispatch:
    push:
        branches:
        - dev-ps
jobs: 
    Docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
              with:
                ref: dev-ps 