name: Run lint tests
on:
    workflow_dispatch:
    issues:
    # push:
    #     branches:
    #         - dev-ps
env:
    PROJECT_DIR: ./nodejs-workflow  ## Set environment variable for project directory
jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
              with:
                ref: dev-ps
            - name: Install dependencies
              working-directory: ${{ env.PROJECT_DIR }}
              run: npm install
            - name: Run ESLint
              working-directory: ${{ env.PROJECT_DIR }}
              #run: npx eslint src/**/*.js
              run: npm run lint
            - name: Build code
              working-directory: ${{ env.PROJECT_DIR }}
              run: npm run build
            - name: Deploy code
              run: echo "Deploying code..."
    output-info:
        needs: lint-test
        runs-on: ubuntu-latest
        steps:
            - name: Output github context
              run: echo "${{ toJson(github.event) }}"
