## This is a reusable workflow that can be called from other workflows
name: Reusable Deploy
on: workflow_call ## this is required for reusable workflows
jobs:
    re-usbale-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: echo "Deploying & uploading as resubale workflow"
